"""add anime table

Revision ID: 16a58d501a59
Revises: a50ed5dd29e2
Create Date: 2026-08-05 15:47:36.693385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a58d501a59'
down_revision: Union[str, Sequence[str], None] = 'a50ed5dd29e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_item_id', sa.Integer(), nullable=False),
    sa.Column('romaji_title', sa.String(), nullable=False),
    sa.Column('english_title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('release_season', sa.String(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_id'), 'anime', ['id'], unique=False)
    op.create_index(op.f('ix_anime_media_item_id'), 'anime', ['media_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anime_media_item_id'), table_name='anime')
    op.drop_index(op.f('ix_anime_id'), table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###
