"""changed anime model

Revision ID: 6ee2d3dfd4b9
Revises: 16a58d501a59
Create Date: 2026-08-06 00:33:01.583468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee2d3dfd4b9'
down_revision: Union[str, Sequence[str], None] = '16a58d501a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manga',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('media_item_id', sa.Integer(), nullable=False),
    sa.Column('romaji_title', sa.String(), nullable=False),
    sa.Column('english_title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('release_season', sa.String(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('chapters', sa.Integer(), nullable=True),
    sa.Column('volumes', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manga_id'), 'manga', ['id'], unique=False)
    op.create_index(op.f('ix_manga_media_item_id'), 'manga', ['media_item_id'], unique=False)
    op.add_column('anime', sa.Column('id_mal', sa.Integer(), nullable=True))
    op.add_column('anime', sa.Column('native_title', sa.String(), nullable=True))
    op.add_column('anime', sa.Column('synonyms', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('anime', sa.Column('format', sa.String(), nullable=True))
    op.add_column('anime', sa.Column('source', sa.String(), nullable=True))
    op.add_column('anime', sa.Column('next_episode_number', sa.Integer(), nullable=True))
    op.add_column('anime', sa.Column('next_episode_airing_at', sa.Integer(), nullable=True))
    op.add_column('anime', sa.Column('trailer_url', sa.String(), nullable=True))
    op.add_column('anime', sa.Column('popularity', sa.Integer(), nullable=True))
    op.add_column('anime', sa.Column('studios', sa.ARRAY(sa.String()), nullable=True))
    op.create_index(op.f('ix_anime_id_mal'), 'anime', ['id_mal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anime_id_mal'), table_name='anime')
    op.drop_column('anime', 'studios')
    op.drop_column('anime', 'popularity')
    op.drop_column('anime', 'trailer_url')
    op.drop_column('anime', 'next_episode_airing_at')
    op.drop_column('anime', 'next_episode_number')
    op.drop_column('anime', 'source')
    op.drop_column('anime', 'format')
    op.drop_column('anime', 'synonyms')
    op.drop_column('anime', 'native_title')
    op.drop_column('anime', 'id_mal')
    op.drop_index(op.f('ix_manga_media_item_id'), table_name='manga')
    op.drop_index(op.f('ix_manga_id'), table_name='manga')
    op.drop_table('manga')
    # ### end Alembic commands ###
