"""changed manga model

Revision ID: f6e9b4ea5017
Revises: 6ee2d3dfd4b9
Create Date: 2026-08-06 00:44:42.820171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e9b4ea5017'
down_revision: Union[str, Sequence[str], None] = '6ee2d3dfd4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga', sa.Column('native_title', sa.String(), nullable=True))
    op.add_column('manga', sa.Column('synonyms', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('manga', sa.Column('background', sa.String(), nullable=True))
    op.add_column('manga', sa.Column('type', sa.String(), nullable=True))
    op.add_column('manga', sa.Column('scored_by', sa.Integer(), nullable=True))
    op.add_column('manga', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('manga', sa.Column('popularity_rank', sa.Integer(), nullable=True))
    op.add_column('manga', sa.Column('members', sa.Integer(), nullable=True))
    op.add_column('manga', sa.Column('favorites', sa.Integer(), nullable=True))
    op.add_column('manga', sa.Column('themes', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('manga', sa.Column('demographics', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('manga', sa.Column('authors', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('manga', sa.Column('serializations', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('manga', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('manga', 'release_season')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga', sa.Column('release_season', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('manga', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('manga', 'serializations')
    op.drop_column('manga', 'authors')
    op.drop_column('manga', 'demographics')
    op.drop_column('manga', 'themes')
    op.drop_column('manga', 'favorites')
    op.drop_column('manga', 'members')
    op.drop_column('manga', 'popularity_rank')
    op.drop_column('manga', 'rank')
    op.drop_column('manga', 'scored_by')
    op.drop_column('manga', 'type')
    op.drop_column('manga', 'background')
    op.drop_column('manga', 'synonyms')
    op.drop_column('manga', 'native_title')
    # ### end Alembic commands ###
